### ISSUE TITLE
Video isn't visible in landscape mode

### ISSUE THREAD

**Issue by imvrs95** [jfilter/frag-den-staat-app#85]
Backm
Project Information
Repository:
https://github.com/jfilter/frag-den-staat-app

Expected behavior
The video was supposed to be visible when rotating the screen to landscape mode while playing video.

Actual behavior
The video is not visible when rotating the screen to landscape mode while playing the video.

How to reproduce

Launch the app

Tap next until the page with a video appears ( tap next for 3 times )

Rotate the screen to landscape mode

Browser/App version: v0.8.1
Operating system:
Android 8.1.0
Model Pixel XL

**Comment by jfilter** [comment]
The Onboarding component I use (https://github.com/jfilter/react-native-onboarding-swiper) has some problems handeling rotations. I don't know any quick fixes and I don't want to spend too much time on it. I may disable landscape view altogether because it just causes problem. I am not sure if people are really using it.

**Comment by jfilter** [comment]
Not a priority.
